// Injected into YouTube page context to access ytInitialPlayerResponse, ytcfg, and Innertube
(function () {
  function getPlayerResponse() {
    try {
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (player && typeof player.getPlayerResponse === 'function') {
        const pr = player.getPlayerResponse();
        if (pr) return pr;
      }
      if (window.ytInitialPlayerResponse) {
        return window.ytInitialPlayerResponse;
      }
      const watchFlexy = document.querySelector('ytd-watch-flexy');
      if (watchFlexy && watchFlexy.playerData) {
        return watchFlexy.playerData;
      }
      if (window.ytplayer && window.ytplayer.config && window.ytplayer.config.args && window.ytplayer.config.args.raw_player_response) {
        return window.ytplayer.config.args.raw_player_response;
      }
    } catch (e) {
      console.warn('[YT-Dictation] Error getting player response:', e);
    }
    return null;
  }

  function extractCaptionTracks() {
    const response = getPlayerResponse();
    if (!response || !response.captions) {
      return [];
    }
    const tracklist = response.captions.playerCaptionsTracklistRenderer || response.captions.playerCaptionsRenderer;
    if (!tracklist || !tracklist.captionTracks) {
      return [];
    }
    return tracklist.captionTracks.map(track => ({
      baseUrl: track.baseUrl,
      name: track.name ? (track.name.simpleText || (track.name.runs && track.name.runs[0]?.text) || 'Phụ đề') : 'Phụ đề',
      languageCode: track.languageCode,
      vssId: track.vssId,
      isAutoGenerated: track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.'))
    }));
  }

  function getVideoInfo() {
    const playerResponse = getPlayerResponse();
    const videoDetails = playerResponse?.videoDetails || {};
    const tracks = extractCaptionTracks();
    const title = videoDetails.title || document.querySelector('h1.ytd-watch-metadata yt-formatted-string')?.textContent || document.title.replace(' - YouTube', '');

    return {
      tracks: tracks,
      videoDetails: {
        title: title || 'Video YouTube',
        videoId: videoDetails.videoId,
        author: videoDetails.author,
        lengthSeconds: videoDetails.lengthSeconds
      }
    };
  }

  // Fetch Innertube get_transcript
  async function fetchInnertubeTranscript() {
    try {
      const apiKey = window.ytcfg?.get('INNERTUBE_API_KEY');
      const context = window.ytcfg?.get('INNERTUBE_CONTEXT');
      
      // Look for getTranscriptEndpoint in ytInitialData or DOM
      let params = null;
      if (window.ytInitialData) {
        const str = JSON.stringify(window.ytInitialData);
        const match = str.match(/"getTranscriptEndpoint":\{"params":"([^"]+)"/);
        if (match) params = match[1];
      }

      if (apiKey && context && params) {
        const res = await window.fetch(`https://www.youtube.com/youtubei/v1/get_transcript?key=${apiKey}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            context: context,
            params: params
          })
        });

        if (res.ok) {
          const data = await res.json();
          const initialSegments = data?.actions?.[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.content?.transcriptSearchPanelRenderer?.body?.transcriptSegmentListRenderer?.initialSegments;
          if (initialSegments && Array.isArray(initialSegments)) {
            const segments = [];
            initialSegments.forEach((item) => {
              const seg = item.transcriptSegmentRenderer;
              if (!seg) return;
              const text = seg.snippet?.runs?.map(r => r.text || '').join('').trim();
              const startMs = parseInt(seg.startMs || '0', 10);
              const endMs = parseInt(seg.endMs || '0', 10);
              if (text) {
                segments.push({
                  id: segments.length,
                  start: parseFloat((startMs / 1000).toFixed(2)),
                  end: parseFloat((endMs / 1000).toFixed(2)),
                  duration: parseFloat(((endMs - startMs) / 1000).toFixed(2)),
                  text: text
                });
              }
            });
            if (segments.length > 0) return segments;
          }
        }
      }
    } catch (e) {
      console.warn('[YT-Dictation] Innertube transcript attempt failed:', e);
    }
    return null;
  }

  window.addEventListener('message', async (event) => {
    if (event.source !== window || !event.data || event.data.source !== 'yt-dictation-cs') {
      return;
    }

    if (event.data.type === 'REQUEST_CAPTIONS_TRACKS') {
      const info = getVideoInfo();
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'RESPONSE_CAPTIONS_TRACKS',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }

    if (event.data.type === 'FETCH_SUBTITLES_IN_PAGE') {
      const requestId = event.data.requestId;
      const baseUrl = event.data.baseUrl;

      // 1. Try Innertube get_transcript first
      const innertubeSegments = await fetchInnertubeTranscript();
      if (innertubeSegments && innertubeSegments.length > 0) {
        window.postMessage({
          source: 'yt-dictation-page',
          type: 'FETCH_SUBTITLES_IN_PAGE_RESPONSE',
          requestId: requestId,
          success: true,
          segments: innertubeSegments
        }, '*');
        return;
      }

      // 2. Try URL variations
      const base = baseUrl.startsWith('//') ? `https:${baseUrl}` : baseUrl;
      const urls = [
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=json3') : `${base}&fmt=json3`,
        base,
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=srv3') : `${base}&fmt=srv3`,
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=srv1') : `${base}&fmt=srv1`,
        base.replace('&variant=gemini', '') + '&fmt=json3',
        base.replace('&variant=gemini', '') + '&fmt=srv3',
        base.replace('&variant=gemini', '')
      ];

      let rawText = null;
      for (const u of urls) {
        try {
          const res = await window.fetch(u);
          if (res.ok) {
            const txt = await res.text();
            if (txt && txt.trim().length > 0) {
              rawText = txt;
              break;
            }
          }
        } catch (e) {}
      }

      window.postMessage({
        source: 'yt-dictation-page',
        type: 'FETCH_SUBTITLES_IN_PAGE_RESPONSE',
        requestId: requestId,
        success: !!rawText,
        rawText: rawText
      }, '*');
    }
  });

  // Notify whenever navigation finishes
  window.addEventListener('yt-navigate-finish', () => {
    setTimeout(() => {
      const info = getVideoInfo();
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'VIDEO_CHANGED',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }, 600);
  });

  // Initial broadcast after load
  setTimeout(() => {
    const info = getVideoInfo();
    if (info.tracks && info.tracks.length > 0) {
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'RESPONSE_CAPTIONS_TRACKS',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }
  }, 1000);
})();
