// Injected into YouTube page context to access ytInitialPlayerResponse & yt player
(function () {
  function getPlayerResponse() {
    try {
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (player && typeof player.getPlayerResponse === 'function') {
        const pr = player.getPlayerResponse();
        if (pr) return pr;
      }
      if (window.ytInitialPlayerResponse) {
        return window.ytInitialPlayerResponse;
      }
      const watchFlexy = document.querySelector('ytd-watch-flexy');
      if (watchFlexy && watchFlexy.playerData) {
        return watchFlexy.playerData;
      }
      if (window.ytplayer && window.ytplayer.config && window.ytplayer.config.args && window.ytplayer.config.args.raw_player_response) {
        return window.ytplayer.config.args.raw_player_response;
      }
    } catch (e) {
      console.warn('[YT-Dictation] Error getting player response:', e);
    }
    return null;
  }

  function extractCaptionTracks() {
    const response = getPlayerResponse();
    if (!response || !response.captions) {
      return [];
    }
    const tracklist = response.captions.playerCaptionsTracklistRenderer || response.captions.playerCaptionsRenderer;
    if (!tracklist || !tracklist.captionTracks) {
      return [];
    }
    return tracklist.captionTracks.map(track => ({
      baseUrl: track.baseUrl,
      name: track.name ? (track.name.simpleText || (track.name.runs && track.name.runs[0]?.text) || 'Phụ đề') : 'Phụ đề',
      languageCode: track.languageCode,
      vssId: track.vssId,
      isAutoGenerated: track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.'))
    }));
  }

  function getVideoInfo() {
    const playerResponse = getPlayerResponse();
    const videoDetails = playerResponse?.videoDetails || {};
    const tracks = extractCaptionTracks();
    const title = videoDetails.title || document.querySelector('h1.ytd-watch-metadata yt-formatted-string')?.textContent || document.title.replace(' - YouTube', '');

    return {
      tracks: tracks,
      videoDetails: {
        title: title || 'Video YouTube',
        videoId: videoDetails.videoId,
        author: videoDetails.author,
        lengthSeconds: videoDetails.lengthSeconds
      }
    };
  }

  window.addEventListener('message', async (event) => {
    if (event.source !== window || !event.data || event.data.source !== 'yt-dictation-cs') {
      return;
    }

    if (event.data.type === 'REQUEST_CAPTIONS_TRACKS') {
      const info = getVideoInfo();
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'RESPONSE_CAPTIONS_TRACKS',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }

    if (event.data.type === 'FETCH_SUBTITLES_IN_PAGE') {
      const requestId = event.data.requestId;
      const baseUrl = event.data.baseUrl;
      const base = baseUrl.startsWith('//') ? `https:${baseUrl}` : baseUrl;

      const urls = [
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=json3') : `${base}&fmt=json3`,
        base,
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=srv3') : `${base}&fmt=srv3`,
        base.includes('fmt=') ? base.replace(/fmt=[^&]+/, 'fmt=srv1') : `${base}&fmt=srv1`
      ];

      let rawText = null;
      for (const u of urls) {
        try {
          const res = await window.fetch(u, { credentials: 'include' });
          if (res.ok) {
            const txt = await res.text();
            if (txt && txt.trim().length > 0) {
              rawText = txt;
              break;
            }
          }
        } catch (e) {
          console.warn('[YT-Dictation] In-page fetch trial failed for:', u, e);
        }
      }

      window.postMessage({
        source: 'yt-dictation-page',
        type: 'FETCH_SUBTITLES_IN_PAGE_RESPONSE',
        requestId: requestId,
        success: !!rawText,
        rawText: rawText
      }, '*');
    }
  });

  // Notify whenever navigation finishes
  window.addEventListener('yt-navigate-finish', () => {
    setTimeout(() => {
      const info = getVideoInfo();
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'VIDEO_CHANGED',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }, 600);
  });

  // Initial broadcast after load
  setTimeout(() => {
    const info = getVideoInfo();
    if (info.tracks && info.tracks.length > 0) {
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'RESPONSE_CAPTIONS_TRACKS',
        tracks: info.tracks,
        videoDetails: info.videoDetails
      }, '*');
    }
  }, 1000);
})();
