// Injected into YouTube page context to access ytInitialPlayerResponse & yt player
(function () {
  function getPlayerResponse() {
    try {
      if (window.ytInitialPlayerResponse) {
        return window.ytInitialPlayerResponse;
      }
      const player = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      if (player && typeof player.getPlayerResponse === 'function') {
        return player.getPlayerResponse();
      }
    } catch (e) {
      console.warn('[YT-Dictation] Error getting player response:', e);
    }
    return null;
  }

  function extractCaptionTracks() {
    const response = getPlayerResponse();
    if (!response || !response.captions) {
      return [];
    }
    const tracklist = response.captions.playerCaptionsTracklistRenderer;
    if (!tracklist || !tracklist.captionTracks) {
      return [];
    }
    return tracklist.captionTracks.map(track => ({
      baseUrl: track.baseUrl,
      name: track.name ? (track.name.simpleText || (track.name.runs && track.name.runs[0]?.text) || 'Unknown') : 'Unknown',
      languageCode: track.languageCode,
      vssId: track.vssId,
      isAutoGenerated: track.kind === 'asr' || (track.vssId && track.vssId.startsWith('a.'))
    }));
  }

  window.addEventListener('message', (event) => {
    if (event.source !== window || !event.data || event.data.source !== 'yt-dictation-cs') {
      return;
    }

    if (event.data.type === 'REQUEST_CAPTIONS_TRACKS') {
      const tracks = extractCaptionTracks();
      const playerResponse = getPlayerResponse();
      const videoDetails = playerResponse?.videoDetails || {};

      window.postMessage({
        source: 'yt-dictation-page',
        type: 'RESPONSE_CAPTIONS_TRACKS',
        tracks: tracks,
        videoDetails: {
          title: videoDetails.title || document.title.replace(' - YouTube', ''),
          videoId: videoDetails.videoId,
          author: videoDetails.author,
          lengthSeconds: videoDetails.lengthSeconds
        }
      }, '*');
    }
  });

  // Notify whenever navigation finishes
  window.addEventListener('yt-navigate-finish', () => {
    setTimeout(() => {
      const tracks = extractCaptionTracks();
      const playerResponse = getPlayerResponse();
      const videoDetails = playerResponse?.videoDetails || {};
      window.postMessage({
        source: 'yt-dictation-page',
        type: 'VIDEO_CHANGED',
        tracks: tracks,
        videoDetails: {
          title: videoDetails.title || document.title.replace(' - YouTube', ''),
          videoId: videoDetails.videoId,
          author: videoDetails.author,
          lengthSeconds: videoDetails.lengthSeconds
        }
      }, '*');
    }, 500);
  });
})();
